name: Build Preview Versions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Build Plugins
        run: |
          chmod +x ./gradlew
          for dir in ./plugins/*; do
            if [ -d "$dir" ]; then
              name=$(basename "$dir")
              ./gradlew :plugins:$name:shadowJar
            fi
          done

      - name: Set up GitHub Actions Artifact CLI client
        uses: lhotari/gh-actions-artifact-client@v2

      - name: Upload Artifacts
        run: |
          for dir in ./plugins/*; do
            if [ -d "$dir" ]; then
              libs="$dir/build/libs"
              name=$(basename "$dir")
              zip -r -j - "$libs" | gh-actions-artifact-client.js upload "allaymc-experimental-${name}"
            fi
          done
